name: VHDL Simulation CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GHDL & GTKWave
        run: |
          sudo apt-get update
          sudo apt-get install -y ghdl gtkwave

      - name: Compile all VHDL
        run: |
          ghdl -a DUT/*.vhd TB/*.vhd

      - name: Run top-level testbench
        run: |
          # מוודאים שהתיקייה קיימת
          mkdir -p simulations
          ghdl -r top_tb --wave=simulations/wave.ghw

      - name: Upload waveform artifact
        uses: actions/upload-artifact@v4
        with:
          name: waveform
          path: simulations/*.ghw
          if-no-files-found: warn
